---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kerberos
# description will be included in the image's metadata
description: Custom Fedora Atomic Image, based off of Bazzite for my Desktop.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bazzite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /
  
  # - type: script
  #   scripts:
  #     - vscode.sh # example: run files/scripts/myscript.sh
  
  - type: dnf
    # repos:
    #   copr:
    #     - atim/starship
    install:
      packages:
        - clang
        # - code
        - golang
        # - libasan
        # - libogg-devel
        # - libusb-compat-0.1
        - lld
        - lldb
        - llvm
        - llvm-devel
        # - mesa-libGLU
        # - nodejs
        - oh-my-posh
        - postgresql-server
        # - qt-creator
        # - qt5-*-devel
        - wine
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: rpm-ostree
    install:
      packages:
        - SDL3-devel
        - SDL3_image-devel
        # - SDL3_mixer-devel
        # - SDL3_net-devel
        - SDL3_ttf-devel

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.wwmm.easyeffects
          - org.keepassxc.KeePassXC
          - app.zen_browser.zen
          - org.libreoffice.LibreOffice
          - dev.vencord.Vesktop
          - com.heroicgameslauncher.hgl
          - com.spotify.Client
          - org.strawberrymusicplayer.Strawberry
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
