---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: kerberos
# description will be included in the image's metadata
description: Custom Fedora Atomic Image, based off of Bazzite for my Desktop.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/blue-build/base-images/fedora-kinoite
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
#  - type: akmods
#    base: main # if not specified, classic "main" base is used by default
#    install:
#      - v4l2loopback
#      - xone

  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    install:
      packages:
        - clang
        - golang
        - lld
        - lldb
        - llvm
        - llvm-devel
        - oh-my-posh
        - postgresql-contrib
        - postgresql-server
        - SDL3-devel
        - SDL3_image-devel
        - SDL3_ttf-devel
        - uupd
        - wine
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

# Working <-
#  - type: rpm-ostree
#    install:
#      - SDL3-devel
#      - SDL3_image-devel
#      - SDL3_ttf-devel

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - com.github.wwmm.easyeffects
          - org.keepassxc.KeePassXC
          - app.zen_browser.zen
          - org.libreoffice.LibreOffice
          - dev.vencord.Vesktop
          - com.heroicgameslauncher.hgl
          - com.spotify.Client
          - org.strawberrymusicplayer.strawberry
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
